apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage
  labels:
    app: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stage
  template:
    metadata:
      labels:
        app: stage
    spec:
      containers:
      - name: stage
        image: nginx
        ports:
        - containerPort: 80
