apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.searchFrontend.appName }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: {{ .Values.searchFrontend.ingressRoute }}
    kind: Rule
    services:
    - name: {{ .Values.searchFrontend.appName }}
      port: {{ .Values.searchFrontend.containerPort }}   
